service: awsdemo # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  standardContactForm:
    handler: contact.contactMe
    events:
     - http:
         path: contact
         method: put
         cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - x-access-token
              - Access-Control-Allow-Origin:'*'
            allowCredentials: true
